// Copyright (c) 2026 Dennis Liu. All rights reserved.

namespace Nvt.Core.Tests.Files;

/// <summary>Generates synthetic content on demand and records each read.</summary>
internal sealed class GeneratedReadStream(
    long length,
    int maximumReadSize = int.MaxValue,
    bool canSeek = true) : Stream
{
    private long _position;

    internal long ReadableLength { get; set; } = length;
    internal long ReportedLength { get; set; } = length;
    internal long TotalBytesRead { get; private set; }
    internal long ReadCalls { get; private set; }
    internal int MaximumRequested { get; private set; }
    internal Action<GeneratedReadStream, int>? AfterRead { get; set; }

    /// <summary>Gets whether the stream supports reading.</summary>
    public override bool CanRead => true;

    /// <summary>Gets whether the stream exposes its length and position.</summary>
    public override bool CanSeek => canSeek;

    /// <summary>Gets whether the stream supports writing.</summary>
    public override bool CanWrite => false;

    /// <summary>Gets the reported length when seeking is supported.</summary>
    public override long Length => canSeek ? ReportedLength : throw new NotSupportedException();

    /// <summary>Gets or sets the position when seeking is supported.</summary>
    public override long Position
    {
        get => canSeek ? _position : throw new NotSupportedException();
        set
        {
            if (!canSeek)
            {
                throw new NotSupportedException();
            }
            _position = value;
        }
    }

    /// <summary>Fills the requested memory with generated bytes unless cancellation was requested.</summary>
    public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return ValueTask.FromResult(Read(buffer.Span));
    }

    /// <summary>Fills part of an array with generated bytes.</summary>
    public override int Read(byte[] buffer, int offset, int count)
    {
        return Read(buffer.AsSpan(offset, count));
    }

    /// <summary>Fills a span with generated bytes and invokes the optional read callback.</summary>
    public override int Read(Span<byte> buffer)
    {
        ReadCalls++;
        MaximumRequested = Math.Max(MaximumRequested, buffer.Length);
        int read = (int)Math.Min(Math.Min(buffer.Length, maximumReadSize), ReadableLength - _position);
        buffer[..read].Fill(0xA5);
        _position = checked(_position + read);
        TotalBytesRead = checked(TotalBytesRead + read);
        AfterRead?.Invoke(this, read);
        return read;
    }

    /// <summary>Throws because flushing is unsupported.</summary>
    public override void Flush()
    {
        throw new NotSupportedException();
    }

    /// <summary>Throws because seeking is unsupported.</summary>
    public override long Seek(long offset, SeekOrigin origin)
    {
        throw new NotSupportedException();
    }

    /// <summary>Throws because changing the length through this method is unsupported.</summary>
    public override void SetLength(long value)
    {
        throw new NotSupportedException();
    }

    /// <summary>Throws because writing is unsupported.</summary>
    public override void Write(byte[] buffer, int offset, int count)
    {
        throw new NotSupportedException();
    }
}
